### ISSUE TITLE
OperationalError('table swdata has no column named _id',)

### ISSUE THREAD

**Issue by pwaller** [scraperwiki/file-upload-tool#6]
@drj11 @scraperdragon when we upload a "DVLA service volumetrics spreadsheet" we get the above error. Any ideas?

**Comment by pwaller** [comment]
It seems that `_id` is specified in `unique_keys=`, but not in `make_row`: https://github.com/scraperwiki/file-upload-tool/blob/2ad3910075763e790cc28c431dc3eb0d7c3b1e09/filter/dvla_service_volumetrics.py#L100

**Comment by drj11** [comment]
It's a bug. We should make sure it has an `_id` column.
